name: System Report

on: workflow_dispatch # allows manual trigger

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:
      - name: OS and kernel
        run: uname -a

      - name: Free disk space
        run: df -h

      - name: Date and time
        run: date

      - name: Install tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Show home directory
        run: tree -L 2 ~

  tool-check:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Create JSON file
        run: echo '{"name":"Anjali","course":"BTech","year":"2"}' > report.json

      - name: Read JSON value
        run: jq '.name' report.json

      - name: Check tool versions
        run: |
          python3 --version
          git --version
          jq --version

      - name: Complete report
        run: echo "Report complete"