name : PR Gatekeeper
on :
    pull_request:
       
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: check the runs
        run: |
              echo "PR on  ${{github.base_ref}} branch is now ready to be merged \n PR number ${{github.event.pull_request.number}}"
              echo "Gatekeeper check complete"

        
