name: Python Inspector

on:
  push:
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Print Python and Pip versions
        run: |
          python --version
          pip --version

      - name: Print Python binary location
        run: which python

      - name: Complete inspection
        run: echo "Inspection complete"
