name : workflow Events

on:
    # push:
    # pull_request:
    # schedule:
    #     - cron: '*/5 * * * *' # runs every 5 minutes
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: echo "Workflow triggered by a(n) ${{github.event_name}} event."
